apiVersion: v1
kind: Secret
metadata:
    name: proxy-service-config-source
    namespace: hm
type: Opaque
stringData:
    config.yaml: |
        log:
          loglevel: warning
        inbounds:
          - listen: "::"
            port: 10443
            protocol: vless
            settings:
              clients:
                - id_secret: OTU5YjBlNmMtMWFiNC00NTRhLWFkOTAtNDI0N2RjYzRkMzI5
                  flow: xtls-rprx-vision
              decryption: none
            streamSettings:
              network: tcp
              security: reality
              realitySettings:
                show: false
                dest: 8.8.8.8:443
                xver: 0
                serverNames:
                  - hackamonth.io
                privateKey_secret: cUhRb1huaUdTTVRoWVQzV0gwMXhQY1I2aTc2VVFlME1EdFM1S042X3BrUQ==
                shortIds_secret:
                  - ZjVlNmNiZDEyOTQzMDZkYw==
                spiderX: /
        outbounds:
          - protocol: freedom
            tag: direct
sops:
    age:
        - recipient: age1xpd0gspqq4d2neww2gwerv8p7mt2v7lyuazk5mmz2677my9rp93qd76ves
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOFdKM3N2SHM2M3ZsWWc2
            cUV0RlBCaW9DSzFWbDNMT0JMZVQrTGgvUFY0Ci9odnFwbUtxTVQ0OXBRY3N0Lzhz
            eXdwNjFuQlk4bFpoUnBVYk1OeEVyZGsKLS0tIEZ6MGVtMnFlSzNTbTNTM0pGb1JG
            TUZoQUoyRDJuMEZOM1FrMUd1K3hRYVkKGvQkKNiHDPdusauDxNBdK57Tg4FAGnbL
            iyMdl0CtL3zfC+KIWB3auLPk0ugDArbhmUHGOElmRao4svikQElcDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T19:14:58Z"
    mac: ENC[AES256_GCM,data:qdpK+eWXPCRSa7MBz4EmvSCV1ML1i0ddG5jLfeavNOmNGgToPgo96Frx4rLdFKkk4bpa9z9KNA7Btr9FFjX/mrTZmCQ9Wj4/lpWKUtH+NR6QYBd5rBOU/t9EQVNY1S10KbY1GA1Ahf2elTiu0Rs3pmfSkshaPNK/VpsmhsRvFt4=,iv:Y5+pD8/mR62Gu1f3nMbK11IrY2WLQ7pIkXYXZ8q2ync=,tag:hbLiJRmMcTkgVeOymK/YNA==,type:str]
    encrypted_regex: .*_secret$
    version: 3.12.2
