apiVersion: v1
kind: Secret
metadata:
    name: proxy-service-config-source
    namespace: hm
type: Opaque
stringData:
    config.yaml: |
        log:
          loglevel: warning
        inbounds:
          - listen: "::"
            port: 10443
            protocol: vless
            settings:
              clients:
                - id_secret: OTU5YjBlNmMtMWFiNC00NTRhLWFkOTAtNDI0N2RjYzRkMzI5
                  flow: xtls-rprx-vision
              decryption: none
            streamSettings:
              network: tcp
              security: reality
              realitySettings:
                show: false
                dest: www.google.com:443
                xver: 0
                serverNames:
                  - hackamonth.io
                privateKey_secret: cUhRb1huaUdTTVRoWVQzV0gwMXhQY1I2aTc2VVFlME1EdFM1S042X3BrUQ==
                shortIds_secret:
                  - ZjVlNmNiZDEyOTQzMDZkYw==
                spiderX: /
        outbounds:
          - protocol: freedom
            tag: direct
sops:
    age:
        - recipient: age1xpd0gspqq4d2neww2gwerv8p7mt2v7lyuazk5mmz2677my9rp93qd76ves
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeFBLREFPTEhZS01XSUpu
            ZzBrcFRQWU5Ldm5NdXNRenFmcGVYWWRSY3lNCkhPQm5FOUdmY29ZT2w2bTN3eEtC
            SmloTkRKR0luVlB0eXpnSmxuNVRGajAKLS0tIGkxbG9KS2ttcUFlRzRNK2tZN1NI
            VGJmdUNUaHY0L3NLb3RmYzd0SXVxNWcK6mZmWno+FzSoV7OooUmJh0VJ/z8D5RR0
            brVcNOfZO/OeE109/2tzOuk2K7fLRnTni/62ZHcU3XGJon586UxMOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T23:03:04Z"
    mac: ENC[AES256_GCM,data:KTUW9vGBSVI4KOtbagNGkx+iEpvma33vTLMFIdGxOuF8uBNTQUfEWnfMRpBRaK1yBfv1wbTp1E69/NCUTHIk1VssiLVuZjV6JrBlqy3KTQbIRCXYlwt6mYvjqTUXKRnBgLelLpj9Z4Z1VvlUNojO5pxtfT7dAlQxcqac8ENjwlY=,iv:XbGlmYnlc14ffUO6tjHfd0DmGzSs92FuimO4H9txxB4=,tag:4dLggnC9H8e91e1RW0Xp2A==,type:str]
    encrypted_regex: .*_secret$
    version: 3.12.2
