apiVersion: v1
kind: Secret
metadata:
    name: proxy-service-config-source
    namespace: hm
type: Opaque
stringData:
    config.yaml: |
        log:
          loglevel: warning
        inbounds:
          - listen: "::"
            port: 10443
            protocol: vless
            settings:
              clients:
                - id_secret: OTU5YjBlNmMtMWFiNC00NTRhLWFkOTAtNDI0N2RjYzRkMzI5
                  flow: xtls-rprx-vision
              decryption: none
            streamSettings:
              network: tcp
              security: reality
              realitySettings:
                show: false
                dest: 1.1.1.1:443
                xver: 0
                serverNames:
                  - hackamonth.io
                privateKey_secret: cUhRb1huaUdTTVRoWVQzV0gwMXhQY1I2aTc2VVFlME1EdFM1S042X3BrUQ==
                shortIds_secret:
                  - ZjVlNmNiZDEyOTQzMDZkYw==
                spiderX: /
        outbounds:
          - protocol: freedom
            tag: direct
sops:
    age:
        - recipient: age1xpd0gspqq4d2neww2gwerv8p7mt2v7lyuazk5mmz2677my9rp93qd76ves
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZEhyUTVGL3VYS1Q5VStM
            bFRYNEt5SjBLNEhUMmhWY0w4OThBOG1Ydng0CjNKV0lrUFRRRXorVkpxM1hlMHpF
            MndSS0JOWlk0WHAwdk9BM3d1cm1palkKLS0tIGxDdk1RaUlyWFZ2Yk9GWGM3UG1N
            cDExSkt3UzZVMWlEWVNlQTlQSHcvdUUKh3VwyAMpwQcGVbAbM87BnZBfvLGvEJ5o
            TRYavBQGmE11QRVOxrYWY9ANQoegCj9Dtsg0KsEshm45Pk0c5N6Jkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T18:48:43Z"
    mac: ENC[AES256_GCM,data:2Ecw3UQKO/ZwVlGfAlBfjuaFV3hqCawRsOYbc3XnxbYw9g4urAN/i0wnph7hS744B8r/QDOCLIa2GK2IqlrNkzEpWGkTzuoDHX790wUiHyxxH1w1mg/HrmF4najLXzBlUWNdFP+hNlRB/xLf+46PlXlN8uvZFzm4QbAk28f0xmU=,iv:0/1rlP3uUusf5kibb2uPMNC25MFJSoCoZvOoGFT5r+s=,tag:BeUd2uU5UDVeLYcwZU8gJw==,type:str]
    encrypted_regex: .*_secret$
    version: 3.12.2
